services:
  bdr-postgresql:
    image: bitnami/postgresql:17
    container_name: bdr_postgres
    environment:
      POSTGRESQL_USERNAME: bdr
      POSTGRESQL_PASSWORD: bdr
      POSTGRESQL_DATABASE: bdr
    ports:
      - "5432:5432"
    volumes:
      - ./schema_sql/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "bdr"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - garage-network

  nginx-static:
    build:
      context: ./src/main/resources
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src/main/resources/static:/usr/share/nginx/html
      - ./src/main/resources/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    networks:
      - garage-network

  spring-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      bdr-postgresql:
        condition: service_healthy
    networks:
      - garage-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://bdr-postgresql:5432/bdr
      SPRING_DATASOURCE_USERNAME: bdr
      SPRING_DATASOURCE_PASSWORD: bdr

volumes:
  postgres_data:
    driver: local

networks:
  garage-network:
    driver: bridge
    name: garage-network
