entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false

tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certificates/traefik.crt
        keyFile: /etc/traefik/certificates/traefik.key

api:
  dashboard: true
  insecure: false
  entryPoint: websecure

http:
  routers:
    http-catchall:
      rule: "HostRegexp(`{host:.+}`)"
      entryPoints:
        - web
      middlewares:
        - redirect-to-https
      service: noop

  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    noop:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1"  # Dummy service